### ISSUE TITLE
Create Sequelize models

### ISSUE THREAD

**Issue by kohlbrr** [kohlbrr/threads#2]

**Comment by guilleasz** [comment]
We can use this package for creating fake data quickly.
https://www.npmjs.com/package/Faker

**Comment by kohlbrr** [comment]
How do we want to break up this workload? I think we could pair so it'd be Hubert + Joon and  Guille  + me (simply going off of who's sitting next to whom)

**Comment by guilleasz** [comment]
That sounds good to me

**Comment by guilleasz** [comment]
We should also make the tests for the models

**Comment by kohlbrr** [comment]
Complete! (as far as we are aware)
