### ISSUE TITLE
Basic express server

### ISSUE THREAD

**Issue by kohlbrr** [kohlbrr/threads#6]

**Comment by kohlbrr** [comment]
Thinking about using `morgan` and `body-parser` in here - any other middleware y'all think would be a good idea to start off with?

**Comment by hubejan** [comment]
passport

**Comment by guilleasz** [comment]
Probably we shouldn't add passport until we have the auth bone workshop on Wednesday

**Comment by guilleasz** [comment]
We should add the config for express.static() in the public folder
