### ISSUE TITLE
Coding standard?

### ISSUE THREAD

**Issue by kohlbrr** [kohlbrr/threads#9]

**Comment by kohlbrr** [comment]
Do we want to hash out a very basic coding standard for us all to abide by? This might be something we can just develop organically as we learn each-others coding styles, or something we want to bang out beforehand.

**Comment by guilleasz** [comment]
I reference this issue to adding an .eslintrc file as style guide:  #7

**Comment by kohlbrr** [comment]
Makes sense - closing
